<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-27 at 12:33:41.
 */
class pure_service_shareTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_service_share
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_service_share;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_service_share::toFacebook
     * @todo   Implement testToFacebook().
     */
    public function testToFacebook() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_service_share::toTwitter
     * @todo   Implement testToTwitter().
     */
    public function testToTwitter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_service_share::toGooglePlus
     * @todo   Implement testToGooglePlus().
     */
    public function testToGooglePlus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
