<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-22 at 16:45:04.
 */
class pure_socialTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_social
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_social;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_social::facebook_share_url
     * @todo   Implement testFacebook_share_url().
     */
    public function testFacebook_share_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_social::twitter_share_url
     * @todo   Implement testTwitter_share_url().
     */
    public function testTwitter_share_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_social::googleplus_share_url
     * @todo   Implement testGoogleplus_share_url().
     */
    public function testGoogleplus_share_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
