<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-22 at 16:45:02.
 */
class pure_htmlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_html
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_html;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_html::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlAttr
     * @todo   Implement testHtmlAttr().
     */
    public function testHtmlAttr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlContent
     * @todo   Implement testHtmlContent().
     */
    public function testHtmlContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlTag
     * @todo   Implement testHtmlTag().
     */
    public function testHtmlTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlTagOpen
     * @todo   Implement testHtmlTagOpen().
     */
    public function testHtmlTagOpen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlTagClose
     * @todo   Implement testHtmlTagClose().
     */
    public function testHtmlTagClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlAttrPluck
     * @todo   Implement testHtmlAttrPluck().
     */
    public function testHtmlAttrPluck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlAddLinks
     * @todo   Implement testHtmlAddLinks().
     */
    public function testHtmlAddLinks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::htmlWrapWords
     * @todo   Implement testHtmlWrapWords().
     */
    public function testHtmlWrapWords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_html::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
