<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-22 at 16:45:02.
 */
class pure_dateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_date;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_date::utc
     * @todo   Implement testUtc().
     */
    public function testUtc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::fromStr
     * @todo   Implement testFromStr().
     */
    public function testFromStr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::daysBetween
     * @todo   Implement testDaysBetween().
     */
    public function testDaysBetween() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::inRange
     * @todo   Implement testInRange().
     */
    public function testInRange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::secondsToHms
     * @todo   Implement testSecondsToHms().
     */
    public function testSecondsToHms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::daysInMonth
     * @todo   Implement testDaysInMonth().
     */
    public function testDaysInMonth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::timeAgo
     * @todo   Implement testTimeAgo().
     */
    public function testTimeAgo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_date::elapsedTime
     * @todo   Implement testElapsedTime().
     */
    public function testElapsedTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
