<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-22 at 16:45:02.
 */
class pure_fsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_fs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_fs;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_fs::getDirSize
     * @todo   Implement testGetDirSize().
     */
    public function testGetDirSize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::rm
     * @todo   Implement testRm().
     */
    public function testRm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::rename
     * @todo   Implement testRename().
     */
    public function testRename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::move
     * @todo   Implement testMove().
     */
    public function testMove() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::getFileMetadata
     * @todo   Implement testGetFileMetadata().
     */
    public function testGetFileMetadata() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::copy
     * @todo   Implement testCopy().
     */
    public function testCopy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::getFileList
     * @todo   Implement testGetFileList().
     */
    public function testGetFileList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::getFolderList
     * @todo   Implement testGetFolderList().
     */
    public function testGetFolderList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::joinFiles
     * @todo   Implement testJoinFiles().
     */
    public function testJoinFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::getMimetype
     * @todo   Implement testGetMimetype().
     */
    public function testGetMimetype() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::getExtension
     * @todo   Implement testGetExtension().
     */
    public function testGetExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::fileRead
     * @todo   Implement testFileRead().
     */
    public function testFileRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_fs::fileReadByLines
     * @todo   Implement testFileReadByLines().
     */
    public function testFileReadByLines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
