<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-22 at 16:45:02.
 */
class pure_strTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_str
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_str;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_str::random
     * @todo   Implement testRandom().
     */
    public function testRandom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::uniqid
     * @todo   Implement testUniqid().
     */
    public function testUniqid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::camelize
     * @todo   Implement testCamelize().
     */
    public function testCamelize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::uncamelize
     * @todo   Implement testUncamelize().
     */
    public function testUncamelize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::slugize
     * @todo   Implement testSlugize().
     */
    public function testSlugize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::unslugize
     * @todo   Implement testUnslugize().
     */
    public function testUnslugize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::clean
     * @todo   Implement testClean().
     */
    public function testClean() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::escape
     * @todo   Implement testEscape().
     */
    public function testEscape() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::concat
     * @todo   Implement testConcat().
     */
    public function testConcat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::truncate
     * @todo   Implement testTruncate().
     */
    public function testTruncate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::truncateWords
     * @todo   Implement testTruncateWords().
     */
    public function testTruncateWords() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::replaceRepeated
     * @todo   Implement testReplaceRepeated().
     */
    public function testReplaceRepeated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isHtml
     * @todo   Implement testIsHtml().
     */
    public function testIsHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isMsWord
     * @todo   Implement testIsMsWord().
     */
    public function testIsMsWord() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isUrl
     * @todo   Implement testIsUrl().
     */
    public function testIsUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isEmail
     * @todo   Implement testIsEmail().
     */
    public function testIsEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isWebFile
     * @todo   Implement testIsWebFile().
     */
    public function testIsWebFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isRegex
     * @todo   Implement testIsRegex().
     */
    public function testIsRegex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::isJson
     * @todo   Implement testIsJson().
     */
    public function testIsJson() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::encrypt
     * @todo   Implement testEncrypt().
     */
    public function testEncrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::decrypt
     * @todo   Implement testDecrypt().
     */
    public function testDecrypt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::hmac
     * @todo   Implement testHmac().
     */
    public function testHmac() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::sha256
     * @todo   Implement testSha256().
     */
    public function testSha256() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::sha512
     * @todo   Implement testSha512().
     */
    public function testSha512() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::base64encode
     * @todo   Implement testBase64encode().
     */
    public function testBase64encode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::base64decode
     * @todo   Implement testBase64decode().
     */
    public function testBase64decode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::compress
     * @todo   Implement testCompress().
     */
    public function testCompress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::uncompress
     * @todo   Implement testUncompress().
     */
    public function testUncompress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_str::parseIniString
     * @todo   Implement testParseIniString().
     */
    public function testParseIniString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
