<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-22 at 16:45:05.
 */
class pure_http_routeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pure_http_route
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pure_http_route;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pure_http_route::param
     * @todo   Implement testParam().
     */
    public function testParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_http_route::isCaseSensitive
     * @todo   Implement testIsCaseSensitive().
     */
    public function testIsCaseSensitive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pure_http_route::isStrictMatch
     * @todo   Implement testIsStrictMatch().
     */
    public function testIsStrictMatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
